# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "capistrano", "3.16.0"

gem "capistrano-multiconfig"
gem "capistrano-env-config"
gem "bcrypt_pbkdf"
gem "ed25519"
gem "capistrano-rvm"
